### PR TITLE
Including a short comment about court chambers

### PR DESCRIPTION
**Pull request by alexandrak018**
I added in CONTRIBUTING.md a short comment regarding the court chambers.

I think making use of them, whenever possible, does help when working on your task (section splitting, in my case).
Dealing with a high number of decisions can quickly become disorganized, especially when they come from different courts all at a time. When working on a single court, I was handling less decisions at once, simplifying the work and helping me improve the results.

Therefore I would suggest profiting from the court chambers, as it helps structuring your work better.  

I tried to keep the comment as short as possible, thus let me know if I should add more details about it.

### CODE REVIEW

**Comment by JoelNiklaus** [comment]
Looks great, thanks. 

I think it would be great if you could add an example (for example together with a link to your code)

**Comment by alexandrak018** [comment]
I changed the comment. I hope it is better now.

**Comment by JoelNiklaus** [comment]
Looks great. Thanks. 
However, I wonder what happens, if we add more code to the section_splitting_functions. I assume, that the line numbers would not be accurate anymore. While the link is very nice, I think it is not very robust. So I guess a textual reference to the example is safer (i.e., BL_Gerichte in section splitting functions together with the link to that file).

**Comment by alexandrak018** [comment]
I thought that might happen, but I found this interesting thing called "canonical url" and they say it should point to the same lines of code, even when adding changes to the file later on.
Here is the link with the info about that:
https://stackoverflow.com/questions/23821235/how-to-link-to-specific-line-number-on-github

Let me know if I should still fix the link, but it should be fine.

**Comment by JoelNiklaus** [comment]
Aah very nice! Didn't know that, sorry.

**Pull request merged**
