### PR TITLE
More tests & improvements for participation extraction

### PR DESCRIPTION
**Pull request by BenjaminBlaesi**
### What & Why

I added more tests so that I could test a broader range of decisions. This allowed me to find some cases where the procedural extraction didn't work as expected. For example, it didn't work for names with an ampersand or a dash. So I added those and also added some additional letter characters to the regex. This allows to find more names.

But I was wondering if it's correct to include titles (such as Dr.) for natural persons in their names. I've included them in the participation extraction but maybe that needs to be changed.

### CODE REVIEW

**Comment by JoelNiklaus** [comment]
Looks good, thanks!

Good point with the titles. I think it would make most sense to add another enum Title (with values Dr., Prof. and maybe others). This enum can then be another field in the data class Person. What do you think?

**Comment by BenjaminBlaesi** [comment]
If the titles are useful information to have, then that makes sense, yes. Though the enum would need a lot of values if you wanted to catch all possible titles.

**Comment by JoelNiklaus** [comment]
Hmm, good question if these titles are useful information. Maybe they could help identify certain people, where multiple people with the same name exists. Otherwise, maybe there are some interesting analyses possible, e.g. if certain legal counsels have a higher success rate than others (which could maybe be partly predicted from the title). I don't know. 

Perhaps it would make sense to just include the most common titles? Say, when they occur at least 100 times? Or just the 20 most common ones?
How many titles did you encounter so far?

**Comment by BenjaminBlaesi** [comment]
I guess I haven't found more than twenty individual titles, just a lot of different combinations. E.g. a Dr. can be combined with a iur. or with  Prof. or it can stand alone. Should each combination be treated as a separate title or would a list of titles for a person make more sense?

**Comment by JoelNiklaus** [comment]
I guess a list of titles would make most sense. Otherwise, we would have a huge explosion of values.

**Comment by BenjaminBlaesi** [comment]
Alright, I have added an enum `Title`, added a list of Title to the `Person` dataclass, adapted the json representation in the `ProceduralParticipation` dataclass, and adapted the `procedural_participation_extracting_functions`. 
Then I added a new test and fixed the rest of the tests.

**Comment by JoelNiklaus** [comment]
Looks great, thank you!

**Pull request merged**
