### PR TITLE
Section splitting for BL_Gerichte

### PR DESCRIPTION
**Pull request by alexandrak018**
Added the section splitting for the following spider: BL_Gerichte.

Results for DE language:
- Header: 6392 / 6399 (99.89%) 
- Facts:  6153 / 6399 (96.16%) 
- Considerations: 6219 / 6399 (97.19%) 
- Rulings:        5326 / 6399 (83.23%) 
- Footer: 46 / 6399 (0.72%)

Remarks:
- only a few have footer
- lots of them are lacking the section "Rulings"
- a few of them are missing one section, or sometimes two
- and for this spider, I found many different types of "formats":
1. [Format 1](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/steuergericht/entscheide-des-steuergerichts-2018/entscheide-in-pdf/2018-03-23-stger-1.pdf/@@download/file/2018-03-23-stger-1.pdf)
2. [Format 2](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/zwangsmassnahmengericht/2012/downloads/2012-03-09_1.pdf/@@download/file/2012-03-09_1.pdf)
3. [Format 3](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/steuergericht/2012/downloads/510_12_21.pdf/@@download/file/510_12_21.pdf)
4. [Format 4](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/enteignungsgericht/entscheide-chronologisch/downloads/11-005.pdf/@@download/file/11-005.pdf)

Here I made a list of decision I believe they are _unwanted_:
1. [Decision 1](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/kantonsgericht/rechtsgebiet/invalidenversicherung/downloads/2017-07-27-sv-7.pdf/@@download/file/2017-07-27-sv-7.pdf)
2. [Decision 2](chung/kantonsgericht/rechtsgebiet/erwerbsersatz/downloads/2020-10-23_sv_1.pdf/@@download/file/2020-10-23_sv_1.pdf)
3. [Decision 3](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/kantonsgericht/rechtsgebiet/invalidenversicherung/downloads/2019-02-13-sv-1.pdf/@@download/file/2019-02-13-sv-1.pdf)
4. [Decision 4](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/kantonsgericht/rechtsgebiet/erwerbsersatz/downloads/2020-10-23_sv_3.pdf/@@download/file/2020-10-23_sv_3.pdf)
5. [Decision 5](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/kantonsgericht/rechtsgebiet/familienzulagen/downloads/2018-09-27-sv-2.pdf/@@download/file/2018-09-27-sv-2.pdf)
6. [Decision 6](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/kantonsgericht/rechtsgebiet/invalidenversicherung/downloads/2019-08-22-sv-5.pdf/@@download/file/2019-08-22-sv-5.pdf)
7. [Decision 7](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/kantonsgericht/rechtsgebiet/arbeitslosenversicherung/downloads/2016-04-28-sv-3.pdf/@@download/file/2016-04-28-sv-3.pdf)
8. [Decision 8](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/kantonsgericht/rechtsgebiet/invalidenversicherung/downloads/2019-09-19-sv-2.pdf/@@download/file/2019-09-19-sv-2.pdf)
9. [Decision 9](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/kantonsgericht/rechtsgebiet/invalidenversicherung/downloads/2016-03-03-sv-2.pdf/@@download/file/2016-03-03-sv-2.pdf)

### CODE REVIEW

**Comment by JoelNiklaus** [comment]
Looks great, thank you very much!

Great, that you spotted the different formats. As far as I understand it, they are due to the different courts, these decisions originate from. Maybe it would have been better if we had devised the section_splitting_functions based on the courts and not the spiders. But then there would have been an even larger explosion of functions. I hope it was still possible with these mixed formats. A thing you could do, is make your code depend on the different formats with if statements based on the court of the decision (you can add it to the namespace here: https://github.com/JoelNiklaus/SwissCourtRulingCorpus/blob/main/scrc/preprocessors/extractors/section_splitter.py#L156 as 'court').

**Comment by alexandrak018** [comment]
I added the if statements with the regular expressions for each court. Let me know if they are alright.

I have a question regarding the BL_XX court. When I tried to see the decisions from BL_XX, there was nothing showing up. Is it that there are no decisions for this court?

Then, I wanted to let you know that I have these links for decisions I can not open ("Failed to load PDF document."):
1. [Link 1](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/steuergericht/2014/downloads/2014-10-24_5301335.pdf/@@download/file/2014-10-24)
2. [Link 2]( https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/steuergericht/2014/downloads/2014-10-03_5301417.pdf/@@download/file/2014-10-03_5301417.pdf)
3. [Link 3](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/steuergericht/2014/downloads/2014-02-14_5301333.pdf/@@download/file/2014-02-14_5301333.pdf)
4. [Link 4](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/steuergericht/2014/downloads/2014-12-05_5301434.pdf/@@download/file/2014-12-05_5301434.pdf)
5. [Link 5]( https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/steuergericht/2014/downloads/2014-12-05_5301430.pdf/@@download/file/2014-12-05_5301430.pdf)
6. [Link 6](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/steuergericht/2014/downloads/2014-11-07_5301414.pdf/@@download/file/2014-11-07_5301414.pdf)
7. [Link 7](https://www.baselland.ch/politik-und-behorden/gerichte/rechtsprechung/steuergericht/2014/downloads/2014-03-28_5301347.pdf/@@download/file/2014-03-28_5301347.pdf)
I am not sure how come I did not see them from the very first time.

I wanted to mention that breaking the decisions into courts made it much easier to work on the task, especially when there are so many types of decisions and things could get messy.

Here are my updated results for DE language:
- Header: 6383 / 6399 (99.75%) 
- Facts:  6125 / 6399 (95.72%) 
- Considerations: 6213 / 6399 (97.09%) 
- Rulings:        5344 / 6399 (83.51%) 
- Footer: 46 / 6399 (0.72%) 
- 
*as I mentioned above, there are quite a few decisions that are missing 'Rulings' which are explaining the not so high percentage for them.

**Comment by JoelNiklaus** [comment]
Good to hear that this splitting made it easier. It would be great if you could add a general short comment in the CONTRIBUTING file describing this new method. I think it can also be applied to the other steps like judicial person extraction and so on. Maybe you could create a separate short PR for that.

The thing with the BL_XX I can well imagine. I think entscheidsuche just added it for any eventualities. So it is very plausible, that there are few or even no decisions there.

I don't know why these links don't work. Perhaps they are stale and when we download the new decisions from entscheidsuche, they work again. But that is not something you need to worry about.

Looks great, thanks for the update and the informative description!

**Comment by alexandrak018** [comment]
Thank you, @JoelNiklaus!
I checked BL_XX one more time and no decision is showing up.  So, I think it should be all right.
Should I still include BL_XX and have the regular expressions have something like a placeholder, like 'empty'? Or do we leave everything as it is? I also made the PR as you mentioned.

**Comment by JoelNiklaus** [comment]
No I think its fine, you have an else in the end which will notify us in case some BL_XX turn up at some point. Thanks.

**Pull request merged**
