### PR TITLE
initial prodigy setup

### PR DESCRIPTION
**Pull request by Skatinger**
## What?
Prodigy is a data labelling tool (other uses as well, but not used here). This PR sets up the basics to use the tool. An example for classifying the decision of the spider `BS_Omni` is included. The data is loaded directly from the `scrc` database, and stored in a separate database called `prodigy`.

## Why?
We do not have any ground-truth, and it might help to get easier validation for results if the ground-truth can easily and quickly be built.

## How?
Using the tool from https://prodi.gy/. Setup details are in the file `./prodigy/readme.md`.

## Testing?
So far it is still in the prototype stage, therefore no tests or similar exist. I did however try it out and managed to pull in data from the database, classify it, save it to the database and dump the results.

## Screenshots 
Dark Theme Example Decision:  
image

Support for mobile:  
image

basic authentication:  
image

## Anything Else?
I would be happy for some feedback what the most important requirements are to make this viable in the end.
So far on the checklist:
- [x] allow customizable input for the dataset:
  - [x] choose the language
  - [x] choose the spider
- [x] add decision id to the prodigy-database entry to later easily match them without rehashing the input
- [ ] proper database retrieval which ensures the same decisions are not retrieved multiple times, but different ones are loaded on each session.
- [ ] retrieve random decisions (instead of ordered) to ensure diversity in the ground truth
- [ ] write the classification result directly to the `scrc` database if a maintainer is the owner of the prodigy session.

**More difficult and maybe not possible in time, but future goals:**
- [ ] easy access to results via scripts and comparer functions for the pipeline to show recognition stats
- [ ] recipes for other tasks (optional, probably not in scope anymore)

### CODE REVIEW

**Comment by JoelNiklaus** [comment]
Thanks for the PR. 

These tasks on the checklist sound very sensible and are important in my opinion. 

In general, I think it would be most valuable for this integration to be applicable for any annotation tasks. The annotation of the extractors are nice to have, but not central. More important are other applications like annotating the explainability for the legal judgment prediction task. I think it would also be necessary to create special tables for the annotations in the database at some point. These annotations would then be used as ground truth in the datasets we create from this database.

I hope this helps.

Just a quick question regarding the images: They show positive and negative as labels. This is just an example but cannot be used directly, right?

**Comment by Skatinger** [comment]
> In general, I think it would be most valuable for this integration to be applicable for any annotation tasks

I will try to write another script to allow more tasks, but first will address the more pressing issues such as options for the first task. Each kind of task needs a separate script, but they are easy to implement.

>  More important are other applications like annotating the explainability for the legal judgment prediction task

I can easily add a field "explanation" which allows free-text. Another option would be to give a multiple-choice selection as well, which allows to select an explanation. Not sure which is better.

> I think it would also be necessary to create special tables for the annotations in the database at some point. 

Absolutely, as soon as the prodigy tool gives useful info, we should address this.

> Just a quick question regarding the images: They show positive and negative as labels. This is just an example but cannot be used directly, right?

It absolutely can be used directly, the screenshots are from the running tool on our server. This is the interface, you can click an option and then "accept" at the bottom, labeling this decision. The result gets stored to the db if you press save at the top left or ctrl+s. Hotkeys work as well, so you can select the option with numbers (1&2 in this case, see right of the boxes for their number). To accept press "a" on the keyboard. That way the mouse is not needed, just the number keys and the "a" key, allowing for much faster labeling.

**Comment by JoelNiklaus** [comment]
Regarding the explanation: It is not yet clear what form this explanation will take. But it may well be that it is in the form of highlighting certain sentences, which speak for a certain judgment outcome. But these details do not have to be your concern right now. It is difficult to determine the exact task now already.

Regarding the direct use: maybe we had a small misunderstanding. I was wondering which task it was? Judgment outcome extraction, judicial person extraction?

**Comment by Skatinger** [comment]
> But it may well be that it is in the form of highlighting certain sentences, which speak for a certain judgment outcome.

Ok, should be pretty easy to do as well, even for someone did not do the initial setup.


> I was wondering which task it was?

The judgment outcome extraction, so in the UI you get the judgment section, and then can say wether the judgment outcome is positive or negative. As far as i understood you intended to have far more fine-grained results for judments, but it was too hard and you opted for positive/negative for a start.

**Comment by JoelNiklaus** [comment]
Great. 

Well, for the final dataset we did not use all the labels so far, but it is definitely the goal to do so at some point. We just simplified it for the first dataset. But during the preprocessing phase, all labels should be recognized nevertheless!

**Comment by Skatinger** [comment]
Ok, I'll use those options then.

image

**Comment by Skatinger** [comment]
I addressed some of the tasks listed in the PR. I think for a first version this is fine.
A few points:

- There is a single recipe (task) for now, to add the capabilities for other tasks concise requirements are required, otherwise its difficult to prepare something. Questions like what should be highlighted, what does the ground-truth actually consist of and what should be the input have to be answered first. For example in the person extraction the functions get the full pdf as splitted sections, so should we just serve a single section which contains the persons, or do we load the full pdf to the prodigy app and the user then has to swipe trough all of it?
- Developing should now be pretty straight forward. Everything is explained in the readme, but basically a docker-image and a corresponding container can be set up with the setup.sh script. Then it can either be run for a specific task with the run.sh script or to develop new tasks / update existing ones the script develop.sh will run a develop environment with a dedicated docker container so the productive one is not disrupted.
- Permissions have to be addressed further, for example who is allowed to label the dataset? Who is allowed to manage the app and allow saving to the database?
- There is no interface to compare the ground truth to the labels. Should be easy once the label is added to the scrc database.
- The run.sh script as well as the docker image etc. are designed to be extendable with other tasks easily.

IMO prodigy is ready to use & customize for labeling judgment outcomes and should serve as a good example on how the other tasks can be implemented once properly defined.

@JoelNiklaus Let me know if something important is missing, I can still take a look next week.

**Pull request merged**
