### PR TITLE
Topic extraction for CH_BGer

### PR DESCRIPTION
**Pull request by ninabaumgartner**
## What?
This PR sets up the topic extraction for CH_BGer in `section_splitting_function.py`. It adds a new section in the correct order to the Section Enum.
There are also some older commits to the prodigy setup which will be overwritten when merging the current prodigy branch.
## Why?
The topic extraction helps to further systematise the judgment by adding a new section. Note that this PR only implements the topic extraction for the CH_BGer.
## How?
To implement the topic extraction the regex marker for the three languages were added to `section_splitting_function.py`. To ensure the correct extraction, the new section has been added to the Section Enum in `section.py`. In addition the order of the sections (as topics are listed before facts in the judgement) was also changed.

```
class Section(Enum):
    FULLTEXT = 1
    HEADER = 2
    FACTS = 3 -----------> TOPIC = 3
    CONSIDERATIONS = 4 --> FACTS = 4
    RULINGS = 5 ---------> CONSIDERATIONS = 5
    FOOTER = 6 ----------> RULINGS = 6
    ... -----------------> FOOTER = 7

```
This addition meant also a change to the database sturcture. Topic was added to `section_type` and the order of the section was also changed to fit the Enum:

section_type_table

Image of the new table structure for section_type.

In order for the `section_type_ids` in the `section table` to correspond with the appropriate text again, the following changes were made:

```SQL
UPDATE public.section
SET section_type_id = 7
WHERE section_type_id = 6;
UPDATE public.section
SET section_type_id = 6
WHERE section_type_id = 5;
UPDATE public.section
SET section_type_id = 5
WHERE section_type_id = 4;
UPDATE public.section
SET section_type_id = 4
WHERE section_type_id = 3;
```
## Testing?
I ran the section_splitter.py pipline for CH_BGer  with the following coverage:
Language.DE of CH_BGer |Language.FR of CH_BGer | Language.IT of CH_BGer
-------- | -------- | --------
Section.HEADER is 81.97%| Section.HEADER is 82.06% | Section.HEADER is 82.56%
Section.TOPIC is 8.63%| Section.TOPIC is 8.61% | Section.TOPIC is 8.36%
Section.FACTS is 61.3%| Section.FACTS is 77.15% | Section.FACTS is 58.23%
Section.CONSIDERATIONS is 81.63%| Section.CONSIDERATIONS is 65.58% | Section.CONSIDERATIONS is 81.383%
Section.RULINGS is 81.53%| Section.RULINGS is 77.87%  |Section.RULINGS is 80.94%
Section.FOOTER is 82.58% | Section.FOOTER is 82.59% | Section.FOOTER is 83.06%

## Screenshots
result_topic_extraction

Excerpt of results in topic extraction

### CODE REVIEW

**Comment by JoelNiklaus** [comment]
Looks great, especially the description is very well formulated!

Have you tested that the downstream pipeline components also work fine after this change?

Could you extend the regexes so that the content of other courts is also captured? 
I made a quick check on entscheidsuche. Many cantons have a topic. They can be detected with keywords like for example "Betreff", "wegen", "Gegenstand".
I guess a general solution would make most sense if possible. This can be added in the extracting functions under XX_SPIDER.

**Comment by ninabaumgartner** [comment]
I will add the additional regexes to XX_SPIDER. I did not test the downstream pipline yet.

**Comment by ninabaumgartner** [comment]
> 
I added the additional regexes to XX_spider in `section_splitting_function.py`.
I testet the downstream pipline with the following results:
- citation_extractor: successfully started and saved some batches of decision, did not terminate (probably due to connection loss)
- judgment_extractor: successfully started and terminated
- lower_court_extractor: successfully started and terminated
- court_composition_extractor: successfully started and saved some batches of decision, did not terminate (probably due to connection loss)
- procedural_participation_extractor: successfully started and saved some batches of decision, did not terminate (probably due to connection loss)
- name_to_gender: successfully started and saved some batches of decision, did not terminate (stoped by me due to a lot of warnings for request limits)

**Comment by JoelNiklaus** [comment]
Great, thank you.

**Pull request merged**
