### PR TITLE
Section splitting for CH_BSTG

### PR DESCRIPTION
**Pull request by alexandrak018**
Added the section splitting for the following spider: CH_BSTG.

Results for DE language:
- Header: 4356 / 4356 (100.00%) 
- Facts:  3390 / 4356 (77.82%) 
- Considerations: 4298 / 4356 (98.67%) 
- Rulings:        4023 / 4356 (92.36%) 
- Footer: 3974 / 4356 (91.23%) 

Results for FR language:
- Header: 2970 / 2970 (100.00%) 
- Facts:  2913 / 2970 (98.08%) 
- Considerations: 2733 / 2970 (92.02%) 
- Rulings:        2661 / 2970 (89.60%) 
- Footer: 2775 / 2970 (93.43%) 

Results for IT language:
- Header: 1144 / 1144 (100.00%) 
- Facts:  1045 / 1144 (91.35%) 
- Considerations: 1004 / 1144 (87.76%) 
- Rulings:        1030 / 1144 (90.03%) 
- Footer: 1080 / 1144 (94.41%) 

Remarks:
- The URLs generated for the PDFs do not work anymore. They did work, a while ago, way before our presentations. Now, whenever I press on one of the [links](https://bstger.weblaw.ch/pdf/TPF-2009-125.pdf), I land on a page with ["404 Not Found"](https://bstger.weblaw.ch/pdf/TPF-2005-73.pdf)
- Related to the point above, I believe that the numbers in the results could be improved a little more, but since I can not check the PDFs anymore, this is all I got. I did check a bunch of decisions and they seem to be sectioned just fine
- There are a few sections missing in the decisions here and there
- There are also a few strange decisions that I did not take care of, that I ignored(random examples from [Entscheidsuche](https://entscheidsuche.ch/), as I can not open the PDFs' URLs anymore):
1.  [Example 1](https://entscheidsuche.ch/docs/CH_BSTG/CH_BSTG_001_TPF-2007-1_2007.pdf#view=FitH)
2.  [Example 2](https://entscheidsuche.ch/docs/CH_BSTG/CH_BSTG_001_TPF-2016-17_2016.pdf#view=FitH)
3.  [Example 3](https://entscheidsuche.ch/docs/CH_BSTG/CH_BSTG_001_TPF-2007-18_2007.pdf#view=FitH)

### CODE REVIEW

**Comment by JoelNiklaus** [comment]
Looks great, thanks!

Do all of the URLs not work anymore?
I quickly looked at Entscheidsuche: https://entscheidsuche.ch/docs/CH_BSTG/. There, the urls work. But they seem to have re-downloaded the entire files again on December 7th 2021. So maybe weblaw changed the urls somehow.

We could maybe redownload the decisions from Entscheidsuche, so that urls work again.

**Comment by alexandrak018** [comment]
No, none of the URLs work anymore.
image

**Comment by Eldnn** [comment]
@alexandrak018 The urls were fetched and updated again this morning and should now work.

**Comment by alexandrak018** [comment]
Thank you, @Eldnn!

Here are the updated results regarding the section splitting for the CH_BSTG spider.

**Results for DE language:**
- Header: 8967 / 8967 (100.00%) 
- Facts:  7229 / 8967 (80.62%) 
- Considerations: 8832 / 8967 (98.49%) 
- Rulings:        8413 / 8967 (93.82%) 
- Footer: 8575 / 8967 (95.63%) 

**Results for FR language:**
- Header: 6133 / 6133 (100.00%) 
- Facts:  6040 / 6133 (98.48%) 
- Considerations: 5781 / 6133 (94.26%) 
- Rulings:        5819 / 6133 (94.88%) 
- Footer: 5927 / 6133 (96.64%)

**Results for IT language:**
- Header: 2372 / 2372 (100.00%) 
- Facts:  2215 / 2372 (93.38%) 
- Considerations: 2150 / 2372 (90.64%) 
- Rulings:        2219 / 2372 (93.55%) 
- Footer: 2307 / 2372 (97.26%)


Some more remarks:
- There are still a few URLs that give me "404 not found"(approx.. 70 such URLs). But I found why:
If the link looks like this https://bstger.weblaw.ch/pdf/TPF201412.pdf, then we get redirected to the 404 not found.
However, if I replace 'pdf' with 'files' inside the URL, then I get to see the decision https://bstger.weblaw.ch/files/TPF201412.pdf .
The thing is, I did try all the links with 404 not found to see how they look, but all of them are URLs to the not so likable decisions [such as](https://bstger.weblaw.ch/files/TPF2014140.pdf).
If it is relevant, I did collect all the links for them, so if they are needed I could share them.
- Here is a list of decisions that I presume they are inconvenient:
1.  [Decision 1](https://bstger.weblaw.ch/files/20120321_SK_2011_5.pdf)
2.  [Decision 2](https://bstger.weblaw.ch/files/20091210_TK_2009_130.pdf)
3.  [Decision 3](https://bstger.weblaw.ch/files/20140523_SN_2014_7.pdf)
4.  [Decision 4](https://bstger.weblaw.ch/files/20080411_TK_2008_45.pdf)

I feel like I must mention it one more time, there are quite a few decisions like this [one](https://bstger.weblaw.ch/files/TPF201184.pdf), but I do not feel too comfortable to manage them. I truly hope that is not an issue.

**Comment by JoelNiklaus** [comment]
Great, thanks for the fast update!

Yes, if you have that list somewhere it would be great, if you could attach it to the PR somehow. 

These four decisions are very special cases. They don't contain any content because they have not been anonymized and thus not published. You don't need to care about them. 

You seem to have managed to split the majority of the decisions, that's amazing!

**Comment by alexandrak018** [comment]
List for GE language:
1. https://bstger.weblaw.ch/pdf/TPF201412.pdf     
2. https://bstger.weblaw.ch/pdf/TPF20123.pdf
3. https://bstger.weblaw.ch/pdf/TPF201816.pdf
4. https://bstger.weblaw.ch/pdf/TPF20198.pdf
5. https://bstger.weblaw.ch/pdf/TPF-2009-12.pdf
6. https://bstger.weblaw.ch/pdf/TPF201011.pdf
7. https://bstger.weblaw.ch/pdf/TPF201111.pdf
8. https://bstger.weblaw.ch/pdf/TPF201039.pdf
9. https://bstger.weblaw.ch/pdf/TPF201517.pdf
10. https://bstger.weblaw.ch/pdf/TPF201820.pdf
11. https://bstger.weblaw.ch/pdf/TPF20204.pdf
12. https://bstger.weblaw.ch/pdf/TPF20107.pdf	
13. https://bstger.weblaw.ch/pdf/TPF20151.pdf
14. https://bstger.weblaw.ch/pdf/TPF201126.pdf
15. https://bstger.weblaw.ch/pdf/TPF201610.pdf
16. https://bstger.weblaw.ch/pdf/TPF201812.pdf
17. https://bstger.weblaw.ch/pdf/TPF201620.pdf
18. https://bstger.weblaw.ch/pdf/TPF201042.pdf
19. https://bstger.weblaw.ch/pdf/TPF20121.pdf
20. https://bstger.weblaw.ch/pdf/TPF201035.pdf 
21. https://bstger.weblaw.ch/pdf/TPF201035.pdf
22. https://bstger.weblaw.ch/pdf/TPF20176.pdf
23. https://bstger.weblaw.ch/pdf/TPF201113.pdf
24. https://bstger.weblaw.ch/pdf/TPF20191.pdf
25. https://bstger.weblaw.ch/pdf/TPF-2007-111.pdf
26. https://bstger.weblaw.ch/pdf/TPF20194.pdf
27. https://bstger.weblaw.ch/pdf/TPF201822.pdf
28. https://bstger.weblaw.ch/pdf/TPF20131.pdf
29. https://bstger.weblaw.ch/pdf/TPF20147.pdf
30. https://bstger.weblaw.ch/pdf/TPF201617.pdf
31. https://bstger.weblaw.ch/pdf/TPF-2009-3.pdf
32. https://bstger.weblaw.ch/pdf/TPF20161.pdf
33. https://bstger.weblaw.ch/pdf/TPF-2010-20.pdf
34. https://bstger.weblaw.ch/pdf/TPF201346.pdf
35. https://bstger.weblaw.ch/pdf/TPF2011112.pdf
36. https://bstger.weblaw.ch/pdf/TPF201914.pdf
37. https://bstger.weblaw.ch/pdf/TPF20181.pdf
38. https://bstger.weblaw.ch/pdf/TPF20111.pdf
39. https://bstger.weblaw.ch/pdf/TPF-2009-15.pdf
40. https://bstger.weblaw.ch/pdf/TPF-2008-189.pdf
41. https://bstger.weblaw.ch/pdf/TPF201044.pdf
42. https://bstger.weblaw.ch/pdf/TPF-2008-1.pdf
43. https://bstger.weblaw.ch/pdf/TPF-2009-1.pdf
44. https://bstger.weblaw.ch/pdf/TPF201514.pdf
45. https://bstger.weblaw.ch/pdf/TPF20115.pdf
46. https://bstger.weblaw.ch/pdf/TPF20201.pdf

**Comment by alexandrak018** [comment]
**List for FR language:**
1. https://bstger.weblaw.ch/pdf/TPF201710.pdf
2. https://bstger.weblaw.ch/pdf/TPF20166.pdf
3. https://bstger.weblaw.ch/pdf/TPF-2010-22.pdf
4. https://bstger.weblaw.ch/pdf/TPF201050.pdf
5. https://bstger.weblaw.ch/pdf/TPF-2008-80.pdf
6. https://bstger.weblaw.ch/pdf/TPF2012144.pdf
7. https://bstger.weblaw.ch/pdf/TPF201628.pdf
8. https://bstger.weblaw.ch/pdf/TPF20101.pdf
9. https://bstger.weblaw.ch/pdf/TPF201047.pdf
10. https://bstger.weblaw.ch/pdf/TPF201212.pdf
11. https://bstger.weblaw.ch/pdf/TPF201217.pdf
12. https://bstger.weblaw.ch/pdf/TPF201015.pdf
13. https://bstger.weblaw.ch/pdf/TPF-2009-17.pdf
14. https://bstger.weblaw.ch/pdf/TPF20118.pdf


**List for IT language:**
1. https://bstger.weblaw.ch/pdf/TPF-2006-287.pdf
2. https://bstger.weblaw.ch/pdf/TPF20171.pdf
3. https://bstger.weblaw.ch/pdf/TPF-2006-236.pdf
4. https://bstger.weblaw.ch/pdf/TPF20141.pdf
5. https://bstger.weblaw.ch/pdf/TPF20208.pdf
6. https://bstger.weblaw.ch/pdf/TPF201029.pdf

**Pull request merged**
